We already finish issue 1 please check it and accept our pull request
HelloYeew/sankasaint-ec pull request #5
Opened 2022-11-04 08:42 UTC by Siraphop4Nene

2022-11-04 09:27 UTC, pontakornth approved these changes
Look good to me.

2022-11-04 10:32 UTC, SainTurDaY27 approved these changes
Good

2022-11-04 10:54 UTC, HelloYeew requested changes

2022-11-04 10:54 UTC, HelloYeew commented on users/views.py
> +# all use -> use
Delete this note

2022-11-04 10:54 UTC, HelloYeew commented on users/views.py
> +    if request.user.is_authenticated and (request.user.is_superuser or request.user.is_staff):
`login_required` annotation already work as a middleware on `is_authenticate`

2022-11-05 06:52 UTC, HelloYeew approved these changes

2022-11-05 06:52 UTC, merged